name: "Publish"
on:
  release:
    types: [published]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "web-ext lint"
        uses: kewisch/action-web-ext@v1
        with:
          cmd: lint
          source: src
          channel: unlisted

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: src

      - name: "Upload package"
        uses: actions/upload-artifact@v4
        with:
          name: extension-package
          path: ${{ steps.web-ext-build.outputs.target }}
          retention-days: 1

  firefox:
    name: "Sign Firefox extension"
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: "Download package"
        id: download-package
        uses: actions/download-artifact@v5
        with:
          name: extension-package

      - name: "web-ext sign AMO"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign

          source: ${{ steps.download-package.outputs.download-path }}
          channel: unlisted

          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          timeout: 900000

      - name: "Attach release assets to release"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # rename the file
          mv ${{ steps.web-ext-sign.outputs.target }} essence-eye.xpi
          gh release upload ${{ github.event.release.tag_name }} essence-eye.xpi
            
  chrome:
    name: "Publish to Chrome Web Store"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Download package"
        id: download-package
        uses: actions/download-artifact@v5
        with:
          name: extension-package

      - name: "Upload to Chrome Web Store"
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: publish
          zip_file: ${{ steps.download-package.outputs.download-path }}
          extension_id: ghhdhjhlnichnicmbjlceoipoomaoebp
          client_id: ${{ secrets.CHROME_PUBLISHER_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_PUBLISHER_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_PUBLISHER_REFRESH_TOKEN }}
